### ISSUE TITLE
Build failures on ConsoleManagerTest (Java 8/Maven 3.3.9)

### ISSUE THREAD

**Issue by jodygarnett** [robward-scisys/sldeditor#1]
See below:

````
Failed tests: 
  ConsoleManagerTest.testExceptionClassOfQException:134 expected:<0> but was:<1>
  ConsoleManagerTest.testExceptionObjectException:150 expected:<0> but was:<1>
  ConsoleManagerTest.testInformation:118 expected:<0> but was:<1>
```

The individual stack traces are not interesting:

````
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.sldeditor.test.unit.common.console.ConsoleManagerTest.testExceptionClassOfQException(ConsoleManagerTest.java:134)
```

Environment:
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Java version: 1.8.0_66, vendor: Oracle Corporation
```

**Comment by robward-scisys** [comment]
Marked unit test as @Ignore for now and will investigate.
Appears log4j output file is not written to the expected file location for the unit test to pick up.

**Comment by robward-scisys** [comment]
Log messages were not flushed to log file consistently.
Updated ConsoleManagerTest and this issue is closed.
