### ISSUE TITLE
ScaleUtilTest fails to due locale dependency

### ISSUE THREAD

**Issue by aaime** [robward-scisys/sldeditor#2]
The build fails on a system with italian locale:

````
Results :

Failed tests: 
  ScaleUtilTest.testGetValue:46 expected:<1:123[,456,]789> but was:<1:123[.456.]789>

Tests run: 265, Failures: 1, Errors: 0, Skipped: 3
````

**Comment by robward-scisys** [comment]
Should now be fixed in the main build.

I'm working on how this project is going to run and how issues are going to be resolved in a more formal manner.
