### ISSUE TITLE
Can't build se-app

### ISSUE THREAD

**Issue by rghosh0** [robward-scisys/sldeditor#224]
I get this output when trying to build, on a 64-bit xenial xubuntu virtual image with 4GB memory:

> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] SLDEditor .......................................... SUCCESS [  0.003 s]
> [INFO] se-app ............................................. FAILURE [ 43.904 s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 44.158 s
> [INFO] Finished at: 2017-01-17T11:11:21-05:00
> [INFO] Final Memory: 18M/265M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project se-app: Could not resolve dependencies for project com.sldeditor:se-app:jar:0.7.0-SNAPSHOT: Failure to find org.dockingframes:docking-frames-common:jar:1.1.2-SNAPSHOT in http://download.osgeo.org/webdav/geotools/ was cached in the local repository, resolution will not be reattempted until the update interval of osgeo has elapsed or updates are forced -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project se-app: Could not resolve dependencies for project com.sldeditor:se-app:jar:0.7.0-SNAPSHOT: Failure to find org.dockingframes:docking-frames-common:jar:1.1.2-SNAPSHOT in http://download.osgeo.org/webdav/geotools/ was cached in the local repository, resolution will not be reattempted until the update interval of osgeo has elapsed or updates are forced

Here is what's reported from mvn -version:

> $ mvn -version
> Warning: JAVA_HOME environment variable is not set.
> Apache Maven 3.3.9
> Maven home: /usr/share/maven
> Java version: 1.8.0_111, vendor: Oracle Corporation
> Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
> Default locale: en_CA, platform encoding: UTF-8
> OS name: "linux", version: "4.4.0-59-generic", arch: "amd64", family: "unix"

**Comment by robward-scisys** [comment]
I tried building it on a clean XUbuntu 16.04 and I reproduced the error.  I've added a repository to the pom and the artifact seems to be downloaded now.
If you do a new pull of the latest code it should now build.

**Comment by rghosh0** [comment]
I'm using 5e462de now, and get this:

> Running com.sldeditor.test.unit.ui.tree.SLDTreeToolsTest
> Warning: Could not get charToByteConverterClass!
> Tests run: 19, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.307 sec <<< FAILURE! - in com.sldeditor.test.unit.ui.tree.SLDTreeToolsTest
> testAddArrows(com.sldeditor.test.unit.ui.tree.SLDTreeToolsTest)  Time elapsed: 0.063 sec  <<< ERROR!
> java.lang.NullPointerException
>         at com.sldeditor.test.unit.ui.tree.SLDTreeToolsTest.testAddArrows(SLDTreeToolsTest.java:1265)
> 
>

**Comment by robward-scisys** [comment]
Submitted a fix, not sure why this didn't get picked up.  Running under a maven build on Windows and XUbuntu didn't show the issue but running the test in Eclipse did.

**Comment by rghosh0** [comment]
Thanks!

> [INFO] SLDEditor .......................................... SUCCESS [  0.007 s]
> [INFO] se-app ............................................. SUCCESS [01:31 min]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
