### ISSUE TITLE
Quotes wrongly added to literal in Filter Dialog

### ISSUE THREAD

**Issue by rghosh0** [robward-scisys/sldeditor#250]
On MacOS, if I
- add a Point symbol
- add a shapefile datasource
- add a filter to the rule, with a PropertyIsEqualTo

The rule never triggers, because even though I omit any quotes from the literal value, the software adds quotes.  These quotes become part of the literal value being matched against, which is not desired.

First, add the literal value without quotes in the Filter Dialog:

![screen shot 2017-01-29 at 8 57 49 am](https://cloud.githubusercontent.com/assets/1896717/22404589/dbd07a18-e601-11e6-8232-f797d3b16f2b.png)

Second, value shows up wrong in the SLD view (quotes shouldn't be there):

![screen shot 2017-01-29 at 8 58 00 am](https://cloud.githubusercontent.com/assets/1896717/22404591/e0bc80da-e601-11e6-80b5-f26cf44b0042.png)

Third, back in the Filter Dialog, quotes show up where they weren't before:

![screen shot 2017-01-29 at 8 58 07 am](https://cloud.githubusercontent.com/assets/1896717/22404592/e47a128c-e601-11e6-9a84-3b6349bdfea4.png)

Here is my system config info:

> bash-3.2$ java -version
> java version "1.8.0_121"
> Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
> bash-3.2$ 
> bash-3.2$ mvn -version
> Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
> Maven home: /usr/local/Cellar/maven/3.3.9/libexec
> Java version: 1.8.0_121, vendor: Oracle Corporation
> Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
> Default locale: en_CA, platform encoding: UTF-8
> OS name: "mac os x", version: "10.12.2", arch: "x86_64", family: "mac"
>

**Comment by robward-scisys** [comment]
Made a fix, if you get the latest source code, the problem should be resolved.

There is a discrepancy within GeoTools between the CQL filter string class and the Filter class.

**Comment by rghosh0** [comment]
Thanks! Works.
