### ISSUE TITLE
Unrecoverable errors

### ISSUE THREAD

**Issue by rghosh0** [robward-scisys/sldeditor#267]
Sometimes there's a failure mode that starts as a user error, but becomes unrecoverable by the application.

Here is an example:
https://drive.google.com/file/d/0B9Kv4E5NP1kFd2pQU0pwa0xtS2s/view?usp=sharing

At 0:28, I neglect to press "Apply" before "Ok".  So the literal in the Rule predicate is null.  But even after I go back to fix it, the application doesn't recover. From this point on, nothing will display in the Map view.

**Comment by robward-scisys** [comment]
I've just uploaded some code to improve the render transformation parameter handling and this issue of incomplete filters causing problems has been fixed as part of this.

**Comment by rghosh0** [comment]
Fixed! Thanks!
