### ISSUE TITLE
text symbolizer properties

### ISSUE THREAD

**Issue by rghosh0** [robward-scisys/sldeditor#270]
Hi, in the latest version, it seems like some text symbolizer properties are ignored.  The "Anchor Point", "Displacement", and "Rotation" fields don't seem to apply to the SLD or Map tabs.

Actually it seems like this isn't always reproducible. I will have to find the sequence of actions that leads to this.

**Comment by rghosh0** [comment]
Sorry this video is so long. It takes a while to reproduce the problem.  I put in two rules, each selecting on a different "type" value ("library" and "school").  I had a textsymbolizer for each.  After that, the results were unexpected.

https://drive.google.com/file/d/0B9Kv4E5NP1kFMmNJVEZaZS10LUk/view?usp=sharing

**Comment by robward-scisys** [comment]
Latest version fixes the issues

**Comment by rghosh0** [comment]
Seems like there's still something wrong.  In this video, both one text symbolizer seems to get overwritten with the settings from another, but neither seem to show up properly in the Map preview.

https://drive.google.com/file/d/0B9Kv4E5NP1kFQ1pudEZZYl9NQzg/view?usp=sharing

**Comment by rghosh0** [comment]
Oops sorry, somehow forgot to pull from git.

**Comment by rghosh0** [comment]
The anchor point (0, 0.5) seems to align the bottom of the label with the point being labeled.

https://drive.google.com/file/d/0B9Kv4E5NP1kFTGxsSjFpUUJMejg/view?usp=sharing

I guess I would expect, for maps, to be able to align by the vertical center of the label.  That also seems to be what the SLD Implementation Spec says.

https://portal.opengeospatial.org/files/?artifact_id=1188

On page 47:

"The AnchorPoint element of a PointPlacement gives the location inside of a label to
use for anchoring the label to the main-geometry point.

...

The coordinates are given as two floating-point numbers in the AnchorPointX and
AnchorPointY elements each with values between 0.0 and 1.0 inclusive. The bounding
box of the label to be rendered is considered to be in a coorindate space from 0.0 (lowerleft
corner) to 1.0 (upper-right corner), and the anchor position is specified as a point in
this space. The default point is X=0, Y=0.5, which is at the middle height of the lefthand
side of the label. "

**Comment by robward-scisys** [comment]
I'm using AnchorPoint.DEFAULT to populate the fields. I've had a look at the GeoTools source code and it is implemented as X=0.5 and Y=0.5 hence why it is being displayed as such.
I'll raise an issue with the GeoTools project to get this clarified and fixed.

**Comment by rghosh0** [comment]
Thanks! By the way, I was curious of your development environment. Do you use eclipse to edit / build / run / debug? I couldn't set up the projects correctly in eclipse for some reason. I don't really use eclipse much at all, so that might be it...

**Comment by robward-scisys** [comment]
Yes I'm using eclipse.  There are a couple of issues when setting up. I've added a [Wiki page](https://github.com/robward-scisys/sldeditor/wiki/Using-Eclipse)

**Comment by rghosh0** [comment]
Thanks for opening the GeoTools issue. I'm putting the link here:
https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-5632

**Comment by robward-scisys** [comment]
The bug raised in GeoTools is now in GeoTools 17-RC1 and also in GeoServer 2.11-RC1

[http://blog.geoserver.org/2017/03/14/geoserver-2-11-rc1-released/](http://blog.geoserver.org/2017/03/14/geoserver-2-11-rc1-released/)

**Comment by rghosh0** [comment]
That's great!
