### ISSUE TITLE
rule scale forgotten

### ISSUE THREAD

**Issue by rghosh0** [robward-scisys/sldeditor#276]
Sometimes the Scale limits for a Rule seem to get forgotten, as in at the end of the following video:

https://drive.google.com/file/d/0B9Kv4E5NP1kFblB5X0t5dmhKY0k/view?usp=sharing

**Comment by robward-scisys** [comment]
I've fixed this in the latest version.

**Comment by rghosh0** [comment]
Fixed! Thanks
