### ISSUE TITLE
unknown filed type class: java.sql.timestamp

### ISSUE THREAD

**Issue by nunoguerreiro** [robward-scisys/sldeditor#358]
unknown filed type class: java.sql.timestamp

timestamp fields are not recognized in SLDEditor

**Comment by robward-scisys** [comment]
Could you provide some more information about what caused this issue please.

**Comment by robward-scisys** [comment]
Pull request #360  adds support for Timestamp fields.
Can you build the latest source code and see if this fixes the issue.
