### ISSUE TITLE
Can't filter rule

### ISSUE THREAD

**Issue by marcelgaucho** [robward-scisys/sldeditor#366]
When I try to Filter a Rule clicking in Edit and then choosing PropertyisEqual, the object comboBox appears empty. I tried this with Postgis and Geopackage layers.

**Comment by robward-scisys** [comment]
Had a look and the datasource field names are not being populated.
What operating system are you running on and I'll get an installer together.

**Comment by robward-scisys** [comment]
The fix is on the master branch so can be built from there.

**Comment by marcelgaucho** [comment]
I am running in Windows 10 and executing sldeditor from the .jar file.

**Comment by marcelgaucho** [comment]
As the issue isso solved, I will close it and build the software from master branch. Thanks for the attention.

**Comment by robward-scisys** [comment]
I've just created a new release.
