### ISSUE TITLE
Unable to open .sld and .sldeditor

### ISSUE THREAD

**Issue by mirandadam** [robward-scisys/sldeditor#41]
Issue:
  I am unable to open .sldeditor files or plain sld files.

How to reproduce:
Method 1:
  Run SLDEditor.jar
  click on File -> Open
  Browse to a previously saved .sldeditor file and open it
  The "file system manager" tree will select the file but no information will appear on the "symbol", "sld", "Map" or "Data Source" tabs to the right.

Method 2:
  Run SLDEditor.jar
  Click on SLD-> Open
  Browse to a previously saved .sld file and open it
  The "file system manager" tree will select the file but no information will appear on the "symbol", "sld", "Map" or "Data Source" tabs to the right.

Method 3:
  Run SLDEditor.jar
  Browse to a previously saved .sld or .sldeditor using the "file system manager" tree.
  Click or double click on the file
  Nothing happens

Environment:
  Windows 10 pro and Oracle Java 1.8.0_91.
  SLDEditor.jar release 0.2.0

**Comment by mirandadam** [comment]
Tested the same on Ubuntu 14.04 and Oracle Java 1.8.0_91 and it seems to work fine.

**Comment by robward-scisys** [comment]
I've tested it on Windows 7 and it works fine.

Does the sld symbol file contain anything 'unusual'? 

Problems could be:
- Something not implemented yet, e.g.
  - UserSymbols
  - Vendor options
- Fonts, either text or TTF
- External graphics
- Data source not connected to

Just created a new issue #42 involving inaccessible Windows drive letters, although I don't think this is the problem in this case.

**Comment by mirandadam** [comment]
Tested on Ubuntu 14.04 virtual machine with OpenJDK build 1.8.0_91-8u91-b14-0ubuntu4~14.04-b14 and it works fine. Will try to take some time today to post Windows 10 console messages.

By the way, thanks for making this available. Awesome work!

**Comment by mirandadam** [comment]
I ran new tests and it seems to be working on Windows 10 now.
I am closing this issue and if I can reproduce the problem I will reopen it with proper support data such as copies of the actual files involved and log messages.
