### ISSUE TITLE
link to MacOS/Windows installers failed

### ISSUE THREAD

**Issue by dorbodwolf** [robward-scisys/sldeditor#429]
fail to link to installers given by Read-me
> MacOS
> An installer is available here: [SLDEditor DMG Installer](https://github.com/robward-scisys/sldeditor/releases/download/0.8.2/SLDEditor-Installer.dmg)
> 
> Windows
> An installer is available here:[ SLDEditor Windows Installer](https://github.com/robward-scisys/sldeditor/releases/download/0.8.2/SLDEditor_installer.exe)

**Comment by robward-scisys** [comment]
Updated the ReadMe.md to point at the correct locations.
